FROM node:latest


# Create app directory
WORKDIR /Frontend-Assets


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./package.json /Frontend-Assets

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY . /Frontend-Assets/

EXPOSE 3000
CMD npm run dev -- --host

# docker run -p 3000:3000 --name -d Fontend-Assets mentor-mentees-connect